## To use this in your game:
# 1. Create an HTML5 export preset (Project > Export > Add...).
# 2. Set the "Export Path" to "export/index.html" (the folder doesn't matter as long as it matches EXPORT_FOLDER_WEB below)
# 3. Set EXPORT_RELEASE_NAME below to whatever you named the preset in Godot
# 4. Default settings should generally work. If you can leave threading support off it will make your life easier. I've not tested if threading works with github pages. I think it requires an extra header to be sent with the requests if threading is on.
# 5. Make sure export_presets.cfg is not .gitignore'd
# 6. Make sure the "export" folder (or whatever you chose in step 2) exists and has at least a .gitkeep file in it. I prefer to put both "/export/*" and "!/export/.gitkeep" in my .gitignore.
# 7. Enable Github Pages for your project (Settings > Pages). Set "Build Source" to "Github Actions" instead of deploying to a specific branch.

# This was adapted from the following sources:
# https://www.vojtechstruhar.com/blog/022-godot-itch-github-action/
# https://github.com/dulvui/godot-4-html-export/blob/main/action.yml
# https://github.com/firebelley/godot-export/tree/master?tab=readme-ov-file

name: Github Pages build
run-name: Building and deploying to GitHub Pages
on:
  push:
    branches: [main]
# uncomment if you want to do nightly builds instead of on every push
# schedule:
#   - cron: '6 7 * * *'  # run daily at 7:06am UTC

env:
  GODOT_VERSION: 4.6
  GODOT_CHANNEL: stable
  GODOT_PROJECT_LOCATION: project.godot
  WORKING_DIRECTORY: .
  EXPORT_FOLDER_WEB: ./export
  EXPORT_RELEASE_NAME: Web

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Godot files
        id: cache-godot
        uses: actions/cache@v3
        with:
          path: |
            ~/.local/share/godot/**
            /usr/local/bin/godot
            ~/.config/godot/**
          key: ${{ runner.os }}-godot-${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}

      - name: Download and config Godot Engine linux server and templates
        shell: bash
        if: steps.cache-godot.outputs.cache-hit != 'true'
        run: |
          wget -q https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_linux.x86_64.zip
          wget -q https://github.com/godotengine/godot-builds/releases/download/${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}/Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_export_templates.tpz
          unzip Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_linux.x86_64.zip
          unzip Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_export_templates.tpz
          mkdir -p ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.${{ env.GODOT_CHANNEL }}
          mkdir -p ~/.config/godot/
          mv templates/* ~/.local/share/godot/export_templates/${{ env.GODOT_VERSION }}.${{ env.GODOT_CHANNEL }}
          rm -f Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_linux.x86_64.zip Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_export_templates.tpz
          mv ./Godot_v${{ env.GODOT_VERSION }}-${{ env.GODOT_CHANNEL }}_linux.x86_64 /usr/local/bin/godot

      - name: Write version file
        shell: bash
        run: echo "dev $(head -c 7 <<< ${GITHUB_SHA}) / $(TZ=America/Los_Angeles date -Is)" > version.txt

      - name: Open project once to import assets in editor mode
        shell: bash
        continue-on-error: true # timeout will exit with code 124
        run: timeout 25 godot --headless --path ${{ env.WORKING_DIRECTORY }} -e

      - name: Export Godot project to html
        shell: bash
        run: godot --headless --path ${{ env.WORKING_DIRECTORY }} --export-release ${{ env.EXPORT_RELEASE_NAME }}

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.EXPORT_FOLDER_WEB }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
